/**
 * generated by Xtext
 */
package de.linma.breakout.ui.contentassist;

import de.linma.breakout.ui.contentassist.AbstractPersistenceProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PersistenceProposalProvider extends AbstractPersistenceProposalProvider {
}
