/*
* generated by Xtext
*/
package de.linma.breakout.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PersistenceGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final RuleCall cPersistenceModelParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Model:
		//	PersistenceModel;
		public ParserRule getRule() { return rule; }

		//PersistenceModel
		public RuleCall getPersistenceModelParserRuleCall() { return cPersistenceModelParserRuleCall; }
	}

	public class PersistenceModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PersistenceModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersistenceModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPersistenceEntitiesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPersistenceEntitiesPersistenceEntityParserRuleCall_3_0 = (RuleCall)cPersistenceEntitiesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PersistenceModel:
		//	"PersistenceModel" name=ID "{" persistenceEntities+=PersistenceEntity* "}";
		public ParserRule getRule() { return rule; }

		//"PersistenceModel" name=ID "{" persistenceEntities+=PersistenceEntity* "}"
		public Group getGroup() { return cGroup; }

		//"PersistenceModel"
		public Keyword getPersistenceModelKeyword_0() { return cPersistenceModelKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//persistenceEntities+=PersistenceEntity*
		public Assignment getPersistenceEntitiesAssignment_3() { return cPersistenceEntitiesAssignment_3; }

		//PersistenceEntity
		public RuleCall getPersistenceEntitiesPersistenceEntityParserRuleCall_3_0() { return cPersistenceEntitiesPersistenceEntityParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class PersistenceEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PersistenceEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersistenceEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Assignment cHasPersistenceNameAssignment_3_0_0 = (Assignment)cGroup_3_0.eContents().get(0);
		private final Keyword cHasPersistenceNamePersistenceNameKeyword_3_0_0_0 = (Keyword)cHasPersistenceNameAssignment_3_0_0.eContents().get(0);
		private final Assignment cPersistenceNameAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cPersistenceNameSTRINGTerminalRuleCall_3_0_1_0 = (RuleCall)cPersistenceNameAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cIdPropertyKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cIdPropertyAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cIdPropertyPropertyParserRuleCall_3_1_1_0 = (RuleCall)cIdPropertyAssignment_3_1_1.eContents().get(0);
		private final Assignment cPropertyAssignment_3_2 = (Assignment)cUnorderedGroup_3.eContents().get(2);
		private final RuleCall cPropertyPropertyParserRuleCall_3_2_0 = (RuleCall)cPropertyAssignment_3_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PersistenceEntity:
		//	"PersistenceEntity" name=ID "{" ((hasPersistenceName?="persistenceName" persistenceName=STRING)? & "idProperty"
		//	idProperty=Property & property+=Property*) "}";
		public ParserRule getRule() { return rule; }

		//"PersistenceEntity" name=ID "{" ((hasPersistenceName?="persistenceName" persistenceName=STRING)? & "idProperty"
		//idProperty=Property & property+=Property*) "}"
		public Group getGroup() { return cGroup; }

		//"PersistenceEntity"
		public Keyword getPersistenceEntityKeyword_0() { return cPersistenceEntityKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//(hasPersistenceName?="persistenceName" persistenceName=STRING)? & "idProperty" idProperty=Property & property+=Property*
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }

		//(hasPersistenceName?="persistenceName" persistenceName=STRING)?
		public Group getGroup_3_0() { return cGroup_3_0; }

		//hasPersistenceName?="persistenceName"
		public Assignment getHasPersistenceNameAssignment_3_0_0() { return cHasPersistenceNameAssignment_3_0_0; }

		//"persistenceName"
		public Keyword getHasPersistenceNamePersistenceNameKeyword_3_0_0_0() { return cHasPersistenceNamePersistenceNameKeyword_3_0_0_0; }

		//persistenceName=STRING
		public Assignment getPersistenceNameAssignment_3_0_1() { return cPersistenceNameAssignment_3_0_1; }

		//STRING
		public RuleCall getPersistenceNameSTRINGTerminalRuleCall_3_0_1_0() { return cPersistenceNameSTRINGTerminalRuleCall_3_0_1_0; }

		//"idProperty" idProperty=Property
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"idProperty"
		public Keyword getIdPropertyKeyword_3_1_0() { return cIdPropertyKeyword_3_1_0; }

		//idProperty=Property
		public Assignment getIdPropertyAssignment_3_1_1() { return cIdPropertyAssignment_3_1_1; }

		//Property
		public RuleCall getIdPropertyPropertyParserRuleCall_3_1_1_0() { return cIdPropertyPropertyParserRuleCall_3_1_1_0; }

		//property+=Property*
		public Assignment getPropertyAssignment_3_2() { return cPropertyAssignment_3_2; }

		//Property
		public RuleCall getPropertyPropertyParserRuleCall_3_2_0() { return cPropertyPropertyParserRuleCall_3_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Keyword cPropertyKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_0_3 = (Group)cGroup_0.eContents().get(3);
		private final Assignment cIsNullableAssignment_0_3_0 = (Assignment)cGroup_0_3.eContents().get(0);
		private final Keyword cIsNullableIsNullableKeyword_0_3_0_0 = (Keyword)cIsNullableAssignment_0_3_0.eContents().get(0);
		private final Assignment cNullableAssignment_0_3_1 = (Assignment)cGroup_0_3.eContents().get(1);
		private final RuleCall cNullableBOOLEANTerminalRuleCall_0_3_1_0 = (RuleCall)cNullableAssignment_0_3_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Keyword cTypeKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cTypeAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cTypeTYPETerminalRuleCall_1_0_1_0 = (RuleCall)cTypeAssignment_1_0_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//Property:
		//	"Property" name=ID "{" (isNullable?="isNullable" nullable=BOOLEAN)? & ("type" type=TYPE) "}";
		public ParserRule getRule() { return rule; }

		//"Property" name=ID "{" (isNullable?="isNullable" nullable=BOOLEAN)? & ("type" type=TYPE) "}"
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }

		//"Property" name=ID "{" (isNullable?="isNullable" nullable=BOOLEAN)?
		public Group getGroup_0() { return cGroup_0; }

		//"Property"
		public Keyword getPropertyKeyword_0_0() { return cPropertyKeyword_0_0; }

		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0_2() { return cLeftCurlyBracketKeyword_0_2; }

		//(isNullable?="isNullable" nullable=BOOLEAN)?
		public Group getGroup_0_3() { return cGroup_0_3; }

		//isNullable?="isNullable"
		public Assignment getIsNullableAssignment_0_3_0() { return cIsNullableAssignment_0_3_0; }

		//"isNullable"
		public Keyword getIsNullableIsNullableKeyword_0_3_0_0() { return cIsNullableIsNullableKeyword_0_3_0_0; }

		//nullable=BOOLEAN
		public Assignment getNullableAssignment_0_3_1() { return cNullableAssignment_0_3_1; }

		//BOOLEAN
		public RuleCall getNullableBOOLEANTerminalRuleCall_0_3_1_0() { return cNullableBOOLEANTerminalRuleCall_0_3_1_0; }

		//("type" type=TYPE) "}"
		public Group getGroup_1() { return cGroup_1; }

		//"type" type=TYPE
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"type"
		public Keyword getTypeKeyword_1_0_0() { return cTypeKeyword_1_0_0; }

		//type=TYPE
		public Assignment getTypeAssignment_1_0_1() { return cTypeAssignment_1_0_1; }

		//TYPE
		public RuleCall getTypeTYPETerminalRuleCall_1_0_1_0() { return cTypeTYPETerminalRuleCall_1_0_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_1() { return cRightCurlyBracketKeyword_1_1; }
	}
	
	
	private ModelElements pModel;
	private TerminalRule tTYPE;
	private TerminalRule tBOOLEAN;
	private PersistenceModelElements pPersistenceModel;
	private PersistenceEntityElements pPersistenceEntity;
	private PropertyElements pProperty;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PersistenceGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.linma.breakout.Persistence".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	PersistenceModel;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//terminal TYPE:
	//	"String" | "Boolean" | "Integer" | "Byte";
	public TerminalRule getTYPERule() {
		return (tTYPE != null) ? tTYPE : (tTYPE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TYPE"));
	} 

	//terminal BOOLEAN:
	//	"true" | "false";
	public TerminalRule getBOOLEANRule() {
		return (tBOOLEAN != null) ? tBOOLEAN : (tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BOOLEAN"));
	} 

	//PersistenceModel:
	//	"PersistenceModel" name=ID "{" persistenceEntities+=PersistenceEntity* "}";
	public PersistenceModelElements getPersistenceModelAccess() {
		return (pPersistenceModel != null) ? pPersistenceModel : (pPersistenceModel = new PersistenceModelElements());
	}
	
	public ParserRule getPersistenceModelRule() {
		return getPersistenceModelAccess().getRule();
	}

	//PersistenceEntity:
	//	"PersistenceEntity" name=ID "{" ((hasPersistenceName?="persistenceName" persistenceName=STRING)? & "idProperty"
	//	idProperty=Property & property+=Property*) "}";
	public PersistenceEntityElements getPersistenceEntityAccess() {
		return (pPersistenceEntity != null) ? pPersistenceEntity : (pPersistenceEntity = new PersistenceEntityElements());
	}
	
	public ParserRule getPersistenceEntityRule() {
		return getPersistenceEntityAccess().getRule();
	}

	//Property:
	//	"Property" name=ID "{" (isNullable?="isNullable" nullable=BOOLEAN)? & ("type" type=TYPE) "}";
	public PropertyElements getPropertyAccess() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
