/*
 * generated by Xtext
 */
package de.linma.breakout.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPersistenceValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.linma.breakout.persistence.PersistencePackage.eINSTANCE);
		return result;
	}
}
