/*
 * generated by Xtext
 */
package de.linma.breakout;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PersistenceRuntimeModule extends de.linma.breakout.AbstractPersistenceRuntimeModule {

}
