/*
* generated by Xtext
*/
package de.linma.breakout;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PersistenceUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.linma.breakout.ui.internal.PersistenceActivator.getInstance().getInjector("de.linma.breakout.Persistence");
	}
	
}
