/**
 * generated by Xtext
 */
package de.linma.breakout.validation;

import de.linma.breakout.validation.AbstractPersistenceValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PersistenceValidator extends AbstractPersistenceValidator {
}
