/*
 * generated by Xtext
 */
package de.linma.breakout.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PersistenceUiModule extends de.linma.breakout.ui.AbstractPersistenceUiModule {
	public PersistenceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
